"use strict";(self.webpackChunkxtd=self.webpackChunkxtd||[]).push([[8557],{3905:(e,t,n)=>{n.d(t,{Zo:()=>p,kt:()=>u});var a=n(67294);function o(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function i(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function r(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?i(Object(n),!0).forEach((function(t){o(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):i(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function s(e,t){if(null==e)return{};var n,a,o=function(e,t){if(null==e)return{};var n,a,o={},i=Object.keys(e);for(a=0;a<i.length;a++)n=i[a],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var i=Object.getOwnPropertySymbols(e);for(a=0;a<i.length;a++)n=i[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var c=a.createContext({}),l=function(e){var t=a.useContext(c),n=t;return e&&(n="function"==typeof e?e(t):r(r({},t),e)),n},p=function(e){var t=l(e.components);return a.createElement(c.Provider,{value:t},e.children)},d={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},h=a.forwardRef((function(e,t){var n=e.components,o=e.mdxType,i=e.originalType,c=e.parentName,p=s(e,["components","mdxType","originalType","parentName"]),h=l(n),u=o,m=h["".concat(c,".").concat(u)]||h[u]||d[u]||i;return n?a.createElement(m,r(r({ref:t},p),{},{components:n})):a.createElement(m,r({ref:t},p))}));function u(e,t){var n=arguments,o=t&&t.mdxType;if("string"==typeof e||o){var i=n.length,r=new Array(i);r[0]=h;var s={};for(var c in t)hasOwnProperty.call(t,c)&&(s[c]=t[c]);s.originalType=e,s.mdxType="string"==typeof e?e:o,r[1]=s;for(var l=2;l<i;l++)r[l]=n[l];return a.createElement.apply(null,r)}return a.createElement.apply(null,n)}h.displayName="MDXCreateElement"},11228:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>c,contentTitle:()=>r,default:()=>d,frontMatter:()=>i,metadata:()=>s,toc:()=>l});var a=n(87462),o=(n(67294),n(3905));const i={},r="Best practices for exceptions (xtd.core)",s={unversionedId:"documentation/Guides/xtd.core/Exceptions/exceptions_best_practices",id:"documentation/Guides/xtd.core/Exceptions/exceptions_best_practices",title:"Best practices for exceptions (xtd.core)",description:"* Handling exceptions",source:"@site/docs/documentation/Guides/xtd.core/Exceptions/exceptions_best_practices.md",sourceDirName:"documentation/Guides/xtd.core/Exceptions",slug:"/documentation/Guides/xtd.core/Exceptions/exceptions_best_practices",permalink:"/xtd/docs/documentation/Guides/xtd.core/Exceptions/exceptions_best_practices",draft:!1,tags:[],version:"current",frontMatter:{},sidebar:"tutorialSidebar",previous:{title:"system exception class and properties (xtd.core)",permalink:"/xtd/docs/documentation/Guides/xtd.core/Exceptions/exception_class_and_properties"},next:{title:"Exceptions",permalink:"/xtd/docs/documentation/Guides/xtd.core/Exceptions/overview"}},c={},l=[{value:"Handling exceptions",id:"handling-exceptions",level:2},{value:"Use try/catch blocks to recover from errors or release resources",id:"use-trycatch-blocks-to-recover-from-errors-or-release-resources",level:3},{value:"Handle common conditions to avoid exceptions",id:"handle-common-conditions-to-avoid-exceptions",level:3},{value:"Call Try* methods to avoid exceptions",id:"call-try-methods-to-avoid-exceptions",level:3},{value:"Catch cancellation and asynchronous exceptions",id:"catch-cancellation-and-asynchronous-exceptions",level:3},{value:"Design classes so that exceptions can be avoided",id:"design-classes-so-that-exceptions-can-be-avoided",level:3},{value:"Restore state when methods don&#39;t complete due to exceptions",id:"restore-state-when-methods-dont-complete-due-to-exceptions",level:3},{value:"Capture and rethrow exceptions properly",id:"capture-and-rethrow-exceptions-properly",level:3},{value:"Throwing exceptions",id:"throwing-exceptions",level:2},{value:"Use predefined exception types",id:"use-predefined-exception-types",level:3},{value:"Use exception builder methods",id:"use-exception-builder-methods",level:3},{value:"Include a localized string message",id:"include-a-localized-string-message",level:3},{value:"Use proper grammar",id:"use-proper-grammar",level:3},{value:"Place throw statements well",id:"place-throw-statements-well",level:3},{value:"Don&#39;t raise exceptions in noexcept methods",id:"dont-raise-exceptions-in-noexcept-methods",level:3},{value:"Throw argument validation exceptions synchronously",id:"throw-argument-validation-exceptions-synchronously",level:3},{value:"Custom exception types",id:"custom-exception-types",level:2},{value:"End exception class names with <code>_exception</code>",id:"end-exception-class-names-with-_exception",level:3},{value:"Include three constructors",id:"include-three-constructors",level:3},{value:"Provide additional properties as needed",id:"provide-additional-properties-as-needed",level:3}],p={toc:l};function d(e){let{components:t,...n}=e;return(0,o.kt)("wrapper",(0,a.Z)({},p,n,{components:t,mdxType:"MDXLayout"}),(0,o.kt)("h1",{id:"best-practices-for-exceptions-xtdcore"},"Best practices for exceptions (xtd.core)"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#handling-exceptions"},"Handling exceptions")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#throwing-exceptions"},"Throwing exceptions")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#custom-exception-types"},"Custom exception types"))),(0,o.kt)("p",null,"Proper exception handling is essential for application reliability.\nYou can intentionally handle expected exceptions to prevent your app from crashing.\nHowever, a crashed app is more reliable and diagnosable than an app with undefined behavior."),(0,o.kt)("p",null,"This article describes best practices for handling and creating exceptions."),(0,o.kt)("h2",{id:"handling-exceptions"},"Handling exceptions"),(0,o.kt)("p",null,"The following best practices concern how you handle exceptions:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#use-try-catch-blocks-to-recover-from-errors-or-release-resources"},"Use try/catch/finally blocks to recover from errors or release resources")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#handle-common-conditions-to-avoid-exceptions"},"Handle common conditions to avoid exceptions")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#call-try-methods-to-avoid-exceptions"},"Call Try* methods to avoid exceptions")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#catch-cancellation-and-asynchronous-exceptions"},"Catch cancellation and asynchronous exceptions")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#design-classes-so-that-exceptions-can-be-avoided"},"Design classes so that exceptions can be avoided")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#restore-state-when-methods-don-t-complete-due-to-exceptions"},"Restore state when methods don't complete due to exceptions")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#capture-and-rethrow-exceptions-properly"},"Capture and rethrow exceptions properly"))),(0,o.kt)("h3",{id:"use-trycatch-blocks-to-recover-from-errors-or-release-resources"},"Use try/catch blocks to recover from errors or release resources"),(0,o.kt)("p",null,"For code that can potentially generate an exception, and when your app can recover from that exception, use ",(0,o.kt)("inlineCode",{parentName:"p"},"try/catch")," blocks around the code.\nIn ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," blocks, always order exceptions from the most derived to the least derived.\n(All exceptions derive from the ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1exception.html"},"xtd::exception")," class.\nMore derived exceptions aren't handled by a ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," clause that's preceded by a ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," clause for a base exception class.)\nWhen your code can't recover from an exception, don't catch that exception. Enable methods further up the call stack to recover if possible."),(0,o.kt)("p",null,"Don't forget to clean up allocated resources when an exception is raised.\nUse the ",(0,o.kt)("a",{parentName:"p",href:"https://en.cppreference.com/w/cpp/language/raii"},"RAII")," idiom for automatic cleanup. "),(0,o.kt)("h3",{id:"handle-common-conditions-to-avoid-exceptions"},"Handle common conditions to avoid exceptions"),(0,o.kt)("p",null,"For conditions that are likely to occur but might trigger an exception, consider handling them in a way that avoids the exception.\nFor example, if you try to close a connection that's already closed, you'll get an ",(0,o.kt)("inlineCode",{parentName:"p"},"invalid_operation_exception"),".\nYou can avoid that by using an ",(0,o.kt)("inlineCode",{parentName:"p"},"if")," statement to check the connection state before trying to close it."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-cpp"},"if (conn.state() != connection_state::closed) {\n  conn.close();\n}\n")),(0,o.kt)("p",null,"If you don't check the connection state before closing, you can catch the ",(0,o.kt)("inlineCode",{parentName:"p"},"invalid_operation_exception")," exception."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-cpp"},"try {\n  conn.close();\n} catch (const invalid_operation_exception& ex) {\n  console::write_line(ex.get_type().full_name());\n  console::write_line(ex.message());\n}\n")),(0,o.kt)("p",null,"The approach to choose depends on how often you expect the event to occur."),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"Use exception handling if the event doesn't occur often, that is, if the event is truly exceptional and indicates an error, such as an unexpected end-of-file. When you use exception handling, less code is executed in normal conditions."),(0,o.kt)("li",{parentName:"ul"},"Check for error conditions in code if the event happens routinely and could be considered part of normal execution. When you check for common error conditions, less code is executed because you avoid exceptions.")),(0,o.kt)("blockquote",null,(0,o.kt)("p",{parentName:"blockquote"},(0,o.kt)("strong",{parentName:"p"},"Notes"),"\nUp-front checks eliminate exceptions most of the time. However, there can be race conditions where the guarded condition changes between the check and the operation, and in that case, you could still incur an exception.")),(0,o.kt)("h3",{id:"call-try-methods-to-avoid-exceptions"},"Call Try* methods to avoid exceptions"),(0,o.kt)("p",null,"If the performance cost of exceptions is prohibitive, some xtd library methods provide alternative forms of error handling.\nFor example, ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1box.html#ae719848b746e3df3c3e5755d87a24c6d"},"xtd::int32_object::parse")," throws an ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1overflow__exception.html"},"xtd::overflow_exception")," if the value to be parsed is too large to be represented by ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/group__types.html#ga205462e259a4eca1545511085c2c350e"},"xtd::int32"),".\nHowever, ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1box.html#a45ebbd8f1e23cadfa07d79b2282205ac"},"xtd::int32_object::try_parse")," doesn't throw this exception. Instead, it returns a boolean and has an ",(0,o.kt)("inlineCode",{parentName:"p"},"out")," parameter that contains the parsed valid integer upon success.\n",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/group__generic__collections.html#gabc6e9eab3efe7d40c7dd9c3287b36960"},"xd::collections::generic::dictionary<key_t,value_t>::try_get_value")," has similar behavior for attempting to get a value from a dictionary."),(0,o.kt)("h3",{id:"catch-cancellation-and-asynchronous-exceptions"},"Catch cancellation and asynchronous exceptions"),(0,o.kt)("p",null,"It's better to catch ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1operation__canceled__exception.html"},"xd::operation_canceled_exception")," instead of ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1threading_1_1tasks_1_1task__canceled__exception.html"},"xtd::threading::tasks::task_canceled_exception"),", which derives from ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1operation__canceled__exception.html"},"xd::operation_canceled_exception"),", when you call an asynchronous method.\nMany asynchronous methods throw an ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1operation__canceled__exception.html"},"xd::operation_canceled_exception")," exception if cancellation is requested.\nThese exceptions enable execution to be efficiently halted and the callstack to be unwound once a cancellation request is observed."),(0,o.kt)("h3",{id:"design-classes-so-that-exceptions-can-be-avoided"},"Design classes so that exceptions can be avoided"),(0,o.kt)("p",null,"A class can provide methods or properties that enable you to avoid making a call that would trigger an exception.\nFor example, the xtd:collections::generic::list class provides methods that help determine the number of items.\nYou can call these methods to avoid the exception that is thrown if you try to access an element outside the range."),(0,o.kt)("p",null,"The following example shows how to access list itemsd without triggering an exception:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-cpp"},"class program {\npublic:\n  // Sums up a list of items using the specified initial value without throwing an exception.\n  static constexpr int accumulate(const list<int>& items, int init_value = 0) noexcept {\n    int result = init_value;\n    // Accesses all elements in the element list using the xtd::collections::generic::list::size method to prevent accessing an element outside the list range.\n    for (xtd::size index = 0; index < items.size(); ++index)\n      result += items[index];\n    return result;\n  }\n};\n")),(0,o.kt)("p",null,"It is also advisable to add the ",(0,o.kt)("inlineCode",{parentName:"p"},"noexcept")," attribute to the method to guarantee the user that the method will not throw an exception."),(0,o.kt)("h3",{id:"restore-state-when-methods-dont-complete-due-to-exceptions"},"Restore state when methods don't complete due to exceptions"),(0,o.kt)("p",null,"Callers should be able to assume that there are no side effects when an exception is thrown from a method.\nFor example, if you have code that transfers money by withdrawing from one account and depositing in another account, and an exception is thrown while executing the deposit, you don't want the withdrawal to remain in effect."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-cpp"},"static void transfer_funds(account& from, &ccount& to, decimal amount) noexcept {\n  from.withdrawal(amount);\n  // If the deposit fails, the withdrawal shouldn't remain in effect.\n  to.deposit(amount);\n}\n")),(0,o.kt)("p",null,"The preceding method doesn't directly throw any exceptions. However, you must write the method so that the withdrawal is reversed if the deposit operation fails."),(0,o.kt)("p",null,"One way to handle this situation is to catch any exceptions thrown by the deposit transaction and roll back the withdrawal."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-cpp"},"static void transfer_funds(account& from, account& to, decimal amount) noexcept {\n  string withdrawal_trx_id = from.withdrawal(amount);\n  try {\n    to.deposit(amount);\n  } catch (...) {\n    from.rollback_transaction(withdrawal_trx_id);\n    throw;\n  }\n}\n")),(0,o.kt)("p",null,"This example illustrates the use of throw to rethrow the original exception, making it easier for callers to see the real cause of the problem without having to examine the ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1exception.html#ad05d51d23eeffcdfd0d86d6668514384"},"inner_exception")," property.\nAn alternative is to throw a new exception and include the original exception as the inner exception."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-cpp"},'static void transfer_funds(account& from, account& to, decimal amount) noexcept {\n  string withdrawal_trx_id = from.withdrawal(amount);\n  try {\n    to.deposit(amount);\n  } catch (const exception& ex) {\n    from.rollback_transaction(withdrawal_trx_id);\n    throw transfer_funds_exception("Withdrawal failed.", ex);\n  }\n}\n')),(0,o.kt)("h3",{id:"capture-and-rethrow-exceptions-properly"},"Capture and rethrow exceptions properly"),(0,o.kt)("p",null,"Once an exception is thrown, part of the information it carries is the stack trace.\nThe stack trace is a list of the method call hierarchy that starts with the method that throws the exception and ends with the method that catches the exception.\nIf you rethrow an exception by specifying the exception in the ",(0,o.kt)("inlineCode",{parentName:"p"},"throw")," statement, for example, ",(0,o.kt)("inlineCode",{parentName:"p"},"throw e"),", the stack trace is restarted at the current method and the list of method calls between the original method that threw the exception and the current method is lost.\nTo keep the original stack trace information with the exception, there are two options that depend on where you're rethrowing the exception from:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"If you rethrow the exception from within the handler (",(0,o.kt)("inlineCode",{parentName:"li"},"catch")," block) that's caught the exception instance, use the throw statement without specifying the exception."),(0,o.kt)("li",{parentName:"ul"},"If you're rethrowing the exception from somewhere other than the handler (",(0,o.kt)("inlineCode",{parentName:"li"},"catch")," block), use ",(0,o.kt)("a",{parentName:"li",href:"."},"xtd::runtime::exception_services::exception_dispatch_info::capture(const xtd:exception&)")," to capture the exception in the handler and ",(0,o.kt)("a",{parentName:"li",href:"."},"xtd::runtime::exception_services::exception_dispatch_info::rerhrow()")," when you want to rethrow it. You can use the ",(0,o.kt)("a",{parentName:"li",href:"."},"xtd::runtime::exception_services::exception_dispatch_info::source_exception")," property to inspect the captured exception.")),(0,o.kt)("p",null,"The following example shows how the ",(0,o.kt)("a",{parentName:"p",href:"."},"xtd::runtime::exception_services::exception_dispatch_info")," class can be used, and what the output might look like."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-cpp"},'auto edi = exception_dispatch_info {};\ntry {\n  auto txt = file::read_all_text("C:\\\\temp\\\\file.txt");\n} catch (const file_not_found_exception& e) {\n  edi = exception_dispatch_info::capture(e);\n}\n\n// ...\n\nconsole::write_line("I was here.");\n\nif (edi.exception_captured())\n  edi.rethrow();\n')),(0,o.kt)("p",null,"If the file in the example code doesn't exist, the following output is produced:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre"},"I was here.\n\nUnhandled exception: xtd::io::file_not_found_exception : Unable to find the specified file.\n   at xtd::io::file::read_all_text [0x0000037C] in C:\\Users\\yves\\Projects\\xtd\\src\\xtd.core\\src\\xtd\\io\\file.cpp:line 225\n   at xtd_console_app::program::main [0x00000080] in C:\\Users\\yves\\Projects\\xtd_console_app\\xtd_console_app\\src\\program.cpp:line 12\n   at xtd::startup::run [0x000000A0] in C:\\Users\\yves\\Projects\\xtd\\src\\xtd.core\\src\\xtd\\startup.cpp:line 157\n   at xtd::startup::internal_safe_run<void (__cdecl*)(xtd::collections::generic::list<xtd::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<xtd::basic_string<char,std::char_traits<char>,std::allocator<char> > > > const &)> [0x000000F8] in C:\\Users\\yves\\Projects\\xtd\\src\\xtd.core\\include\\xtd\\startup.h:line 105\n   at xtd::startup::safe_run [0x0000009C] in C:\\Users\\yves\\Projects\\xtd\\src\\xtd.core\\src\\xtd\\startup.cpp:line 70\n   at main [0x0000003C] in C:\\Users\\yves\\Projects\\xtd_console_app\\xtd_console_app\\properties\\startup.cpp:line 10\n")),(0,o.kt)("h2",{id:"throwing-exceptions"},"Throwing exceptions"),(0,o.kt)("p",null,"The following best practices concern how you throw exceptions:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#use-predefined-exception-types"},"Use predefined exception types")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#use-exception-builder-methods"},"Use exception builder methods")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#include-a-localized-string-message"},"Include a localized string message")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#use-proper-grammar"},"Use proper grammar")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#place-throw-statements-well"},"Place throw statements well")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#don-t-raise-exceptions-in-noexcept-methods"},"Don't raise exceptions in noexcept methods")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#throw-argument-validation-exceptions-synchronously"},"Throw argument validation exceptions synchronously"))),(0,o.kt)("h3",{id:"use-predefined-exception-types"},"Use predefined exception types"),(0,o.kt)("p",null,"Introduce a new exception class only when a predefined one doesn't apply. For example:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},"If a property set or method call isn't appropriate given the object's current state, throw an ",(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1invalid__operation__exception.html"},"xtd::invalid_operation_exception")," exception."),(0,o.kt)("li",{parentName:"ul"},"If invalid parameters are passed, throw an ",(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__exception.html"},"xtd::argument_exception")," exception or one of the predefined classes that derive from ",(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__exception.html"},"xtd::argument_exception"),".")),(0,o.kt)("blockquote",null,(0,o.kt)("p",{parentName:"blockquote"},(0,o.kt)("strong",{parentName:"p"},"Notes"),"\nWhile it's best to use predefined exception types when possible, you shouldn't raise some reserved exception types, such as ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1access__violation__exception.html"},"xtd::access_violation_exception"),", ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1index__out__of__range__exception.html"},"xtd::index_out_of_range_exception"),", and ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1null__pointer__exception.html"},"xtd::null_pointer_exception"),". See ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/group__exceptions.html"},"exceptions")," to view all xtd exceptions.")),(0,o.kt)("h3",{id:"use-exception-builder-methods"},"Use exception builder methods"),(0,o.kt)("p",null,"It's common for a class to throw the same exception from different places in its implementation.\nTo avoid excessive code, create a helper method that creates the exception and returns it.\nFor example:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-cpp"},'class file_reader {\npublic:\n  file_reader(const string& path) noexcept : file_name_ {path} {}\n\n  optional<array<byte>> read(int bytes) {\n    optional<array<byte>> results = file_utils.read_from_file(file_name_, bytes);\n    if (!results) throw file_reader_exception();\n    return results;\n  }\n\n  static file_io_exception file_reader_exception() noexcept {\n    string description = "My file_reader_exception description";\n    return file_io_exception {description};\n  }\n\nprivate:\n  string file_name_;\n};\n')),(0,o.kt)("p",null,"Some key xtd exception types have such static throw helper methods that allocate and throw the exception.\nYou should call these methods instead of constructing and throwing the corresponding exception type:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__null__exception.html#a2238e664c08b9a214361494544a9dee7"},"xtd::argument_null_exception::throw_if_null")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__exception.html#aa904822ef2bb340d8b5ac44d4c452b32"},"xtd::argument_exception::throw_if_empty")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__exception.html#a73af69f77f9705387150935434a8e709"},"xtd::argument_exception::throw_if_empty_or_white_space")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__out__of__range__exception.html#a2882385050c42bf510bec42ee8177983"},"xtd::argument_out_of_range_exception::throw_if_zero")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__out__of__range__exception.html#aaef683b1532f1016a2aae21836a486ed"},"xtd::argument_out_of_range_exception::throw_if_negative")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__out__of__range__exception.html#a0ca0b3dd187796f1b2bb03846d73c5b5"},"xtd::argument_out_of_range_exception::throw_if_positive")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__out__of__range__exception.html#a84bda1e0473c5515ee86b869c33db9d8"},"xtd::argument_out_of_range_exception::throw_if_equal")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__out__of__range__exception.html#a2a631cb65cbd57eebe3b2330af3aeda1"},"xtd::argument_out_of_range_exception::throw_if_less_than")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__out__of__range__exception.html#a8c0a02040287a3142ca095b11fade612"},"xtd::argument_out_of_range_exception::throw_if_not_equal")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__out__of__range__exception.html#a4fd301574e5c0e079ba93a0ca7d69d50"},"xtd::argument_out_of_range_exception::throw_if_negative_or_zero")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__out__of__range__exception.html#a4dbf51ceefb8e881778ce0fa26baf2d7"},"xtd::argument_out_of_range_exception::throw_if_positive_or_zero")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__out__of__range__exception.html#ab46390f7974712fd8f942ba36b63faaf"},"xtd::argument_out_of_range_exception::throw_if_greater_than")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__out__of__range__exception.html#a120e488fa6378121a110404733282f98"},"xtd::argument_out_of_range_exception::throw_if_less_than_or_equal")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__out__of__range__exception.html#a665d7e453ad6aab6cc61f182a4906e3b"},"xtd::argument_out_of_range_exception::throw_if_greater_than_or_equal"))),(0,o.kt)("p",null,"If you're implementing an asynchronous method, call ",(0,o.kt)("a",{parentName:"p",href:"."},"xtd::threading::cancellation_token::throw_if_cancellation_requested()")," instead of checking if cancellation was requested and then constructing and throwing ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1operation__canceled__exception.html"},"operation_canceled_exception"),"."),(0,o.kt)("h3",{id:"include-a-localized-string-message"},"Include a localized string message"),(0,o.kt)("p",null,"The error message the user sees is derived from the ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1exception.html#a472b56575bd47dbd829931c900a16600"},"xtd::exception::message")," property of the exception that was thrown, and not from the name of the exception class.\nTypically, you assign a value to the ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1exception.html#a472b56575bd47dbd829931c900a16600"},"xtd::exception::message")," property by passing the message string to the message argument of an ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1exception.html"},"xtd::exception")," constructor."),(0,o.kt)("p",null,"For localized applications, you should provide a localized message string for every exception that your application can throw.\nYou use ",(0,o.kt)("inlineCode",{parentName:"p"},"locale")," files to provide localized error messages.\nFor information on localizing applications and retrieving localized strings, see the following article:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"/docs/documentation/Guides/xtd.core/internationalization"},"Internationalization"))),(0,o.kt)("h3",{id:"use-proper-grammar"},"Use proper grammar"),(0,o.kt)("p",null,"Write clear sentences and include ending punctuation.\nEach sentence in the string assigned to the ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1exception.html#a472b56575bd47dbd829931c900a16600"},"xtd::exception::message"),' property should end in a period.\nFor example, "The log table has overflowed." uses correct grammar and punctuation.'),(0,o.kt)("h3",{id:"place-throw-statements-well"},"Place throw statements well"),(0,o.kt)("p",null,"Place throw statements where the stack trace will be helpful.\nThe stack trace begins at the statement where the exception is thrown and ends at the catch statement that catches the exception."),(0,o.kt)("h3",{id:"dont-raise-exceptions-in-noexcept-methods"},"Don't raise exceptions in noexcept methods"),(0,o.kt)("p",null,"Don't raise exceptions in noexcept methods. For example:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-cpp"},"void the_method() noexcept {\n  throw argument_exception {}; // Error because you specify to the user that the_method has no exception, yet you throw an exception.\n}\n")),(0,o.kt)("h3",{id:"throw-argument-validation-exceptions-synchronously"},"Throw argument validation exceptions synchronously"),(0,o.kt)("p",null,"In task-returning methods, you should validate arguments and throw any corresponding exceptions, such as ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__exception.html"},"xtd::argument_exception")," and ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1argument__null__exception.html"},"xtd::argument_null_exception"),", before entering the asynchronous part of the method.\nExceptions that are thrown in the asynchronous part of the method are stored in the returned task and don't emerge until, for example, the task is awaited."),(0,o.kt)("h2",{id:"custom-exception-types"},"Custom exception types"),(0,o.kt)("p",null,"The following best practices concern custom exception types:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#end-exception-class-names-with-exception"},"End exception class names with ",(0,o.kt)("inlineCode",{parentName:"a"},"_exception"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#include-three-constructors"},"Include three constructors")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"#provide-additional-properties-as-needed"},"Provide additional properties as needed"))),(0,o.kt)("h3",{id:"end-exception-class-names-with-_exception"},"End exception class names with ",(0,o.kt)("inlineCode",{parentName:"h3"},"_exception")),(0,o.kt)("p",null,"When a custom exception is necessary, name it appropriately and derive it from the ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1exception.html"},"xtd::exception")," class. For example:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-cpp"},"class my_file_not_found_exception : public xtd::exception {\n\n};\n")),(0,o.kt)("h3",{id:"include-three-constructors"},"Include three constructors"),(0,o.kt)("p",null,"Use at least the three common constructors when creating your own exception classes: the parameterless constructor, a constructor that takes a string message, and a constructor that takes a string message and an inner exception."),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1exception.html#a292b8c4b43580256fdb1513113a20fca"},"xtd::exception(const xtd::diagnostics::stack_frame &information=xtd::diagnostics::stack_frame::empty())"),", which uses default values and optional stack frame."),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1exception.html#ad43693d8a3723ec0b995123b2d14a297"},"xtd::exception(const xtd::string &message, const xtd::diagnostics::stack_frame &information=xtd::diagnostics::stack_frame::empty())"),", which accepts a string message and optional stack frame."),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1exception.html#a946c0dec93a72997929197b1699e7040"},"xtd::exception(const xtd::string &message, const std::exception &inner_exception, const xtd::diagnostics::stack_frame &information=xtd::diagnostics::stack_frame::empty())"),", which accepts a string message, an inner exception and optional stack frame.")),(0,o.kt)("p",null,"For an example, see ",(0,o.kt)("a",{parentName:"p",href:"/docs/documentation/Guides/xtd.core/Exceptions/How-tos/create_user_defined_exceptions"},"How to: Create user-defined exceptions"),"."),(0,o.kt)("h3",{id:"provide-additional-properties-as-needed"},"Provide additional properties as needed"),(0,o.kt)("p",null,"Provide additional properties for an exception (in addition to the custom message string) only when there's a programmatic scenario where the additional information is useful.\nFor example, the ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1io_1_1file__not__found__exception.html"},"xtd::io::file_not_found_exception")," provides the ",(0,o.kt)("a",{parentName:"p",href:"https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1io_1_1file__not__found__exception.html#a7cd16d6b427a9f14245ad77bcc19b4eb"},"file_name")," property."),(0,o.kt)("h1",{id:"see-also"},"See also"),(0,o.kt)("p",null,"\u200b"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"/docs/documentation/Guides/xtd.core/Exceptions/overview"},"Exceptions")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"/docs/documentation/Guides"},"Guides")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("a",{parentName:"li",href:"/docs/documentation"},"Documentation"))))}d.isMDXComponent=!0}}]);